apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site-{{ .Release.Name }}
  labels:
    app: static-site
    site: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: static-site
      site: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: static-site
        site: {{ .Release.Name }}
        git_revision: {{ .Values.repo.revision }}
    spec:
      initContainers:
        - name: git
          image: jijiechen/alpine-curl-git:v2.24.1
          workingDir: /website
          command: ["git"]
          args: ["clone", "--single-branch", "--branch", "{{ .Values.repo.branch }}", "{{ .Values.repo.location }}", "."]
          volumeMounts:
            - name: website
              mountPath: /website
      containers:
        - name: nginx
          image: nginx:1.17.9-alpine
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          command: ["/bin/sh"]
          args: ["-c", "mkdir -p /tmp/log/nginx/ && exec nginx -g 'daemon off;'"]
          resources:
            limits:
              cpu: 200m
              memory: "200Mi"
            requests:
              cpu: 50m
              memory: "100Mi"
          volumeMounts:
            - name: website
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: website
          emptyDir: {}
        - name: config
          configMap:
            name: static-site-config-{{ .Release.Name }}
